# The URL the site will be built for
base_url = "https://www.shinyu-corp.com"
theme = "apollo"
taxonomies = [{ name = "tags" }]

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true
minify_html = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]

[markdown.highlighting]
theme = "catppuccin-mocha"

# custom 
[extra]
toc = false

socials = [
  # Configure socials here
]

menu = [
  { name = "ホーム", url = "/", weight = 1 },
  { name = "ブログ", url = "/posts", weight = 2 },
  { name = "会社概要", url = "/company", weight = 3 },
]
